import { readdir, readFile, realpath, stat } from "node:fs/promises"
import path from "node:path"
const MAX_FILES = 300
const MAX_BYTES = 512 * 1024
const MAX_OUTPUT = 12000
const SCRIPT_EXTENSIONS = new Set([".sh", ".bash", ".zsh", ".fish", ".py", ".pl", ".rb", ".php", ".js", ".mjs", ".cjs", ".ts", ".ps1"])
const SKIP = new Set([".git", "node_modules", "dist", "build", "coverage", ".next", ".cache"])
const SENSITIVE_NAMES = /^(?:\.env(?:\..*)?|credentials(?:\..*)?|secrets?(?:\..*)?|.*\.pem|.*\.key)$/i
export class SherpaError extends Error {}
async function root(input: string): Promise<string> { const configured = process.env.SHEBANG_SHERPA_ROOT ?? path.join(process.cwd(), ".."); const allowed = await realpath(path.resolve(configured)).catch(() => path.resolve(configured)); const target = await realpath(path.resolve(allowed, input || ".")).catch(() => path.resolve(allowed, input || ".")); const relative = path.relative(allowed, target); if (relative.startsWith("..") || path.isAbsolute(relative)) throw new SherpaError("Project path must stay inside the configured local workspace"); const info = await stat(target).catch(() => null); if (!info?.isDirectory()) throw new SherpaError("Project directory is unavailable"); return target }
function category(line: string): string { const lower = line.toLowerCase(); if (lower.includes("/usr/bin/env python") || lower.includes("/python")) return "python"; if (lower.includes("/usr/bin/env node") || lower.includes("node")) return "node"; if (lower.includes("/usr/bin/env bash") || lower.includes("/bash")) return "bash"; if (lower.includes("/usr/bin/env sh") || /\/sh\b/.test(lower)) return "posix-sh"; if (lower.includes("ruby")) return "ruby"; if (lower.includes("perl")) return "perl"; if (lower.includes("powershell") || lower.includes("pwsh")) return "powershell"; if (lower.includes("fish")) return "fish"; return "other" }
function warning(line: string, executable: boolean): string[] { const result: string[] = []; const lower = line.toLowerCase(); if (!executable) result.push("missing-executable-bit"); if (line.startsWith("#!") && !line.includes("/usr/bin/env") && /\/usr\/local|\/opt\/homebrew|\/home\/|\/Users\//.test(line)) result.push("machine-specific-interpreter-path"); if (lower.includes("python2") || lower.includes("nodejs")) result.push("legacy-interpreter-name"); if (lower.includes("/bin/bash") || lower.includes("/bin/sh")) result.push("absolute-system-interpreter"); return result }
async function collect(directory: string, result: string[], depth = 0): Promise<void> { if (depth > 5 || result.length >= MAX_FILES) return; let entries; try { entries = await readdir(directory, { withFileTypes: true }) } catch { return } for (const entry of entries) { if (SKIP.has(entry.name)) continue; const full = path.join(directory, entry.name); const resolved = await realpath(full).catch(() => ""); if (!resolved || path.relative(directory, resolved).startsWith("..")) continue; if (entry.isDirectory()) await collect(resolved, result, depth + 1); else if (!SENSITIVE_NAMES.test(entry.name) && SCRIPT_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) result.push(resolved); if (result.length >= MAX_FILES) return } }
export async function inspectScripts(input: string): Promise<Record<string, unknown>> { const directory = await root(input); const files: string[] = []; await collect(directory, files); const interpreterCounts: Record<string, number> = {}; const warningCounts: Record<string, number> = {}; let candidateCount = 0; let shebangCount = 0; let executableCount = 0; let unreadableCount = 0; for (const file of files) { let bytes; try { bytes = await readFile(file); if (bytes.byteLength > MAX_BYTES) continue } catch { unreadableCount += 1; continue } const firstLine = bytes.toString("utf8").split(/\r?\n/, 1)[0] ?? ""; const mode = (await stat(file)).mode; const executable = Boolean(mode & 0o111); if (firstLine.startsWith("#!")) { candidateCount += 1; shebangCount += 1; executableCount += executable ? 1 : 0; const kind = category(firstLine); interpreterCounts[kind] = (interpreterCounts[kind] ?? 0) + 1; for (const item of warning(firstLine, executable)) warningCounts[item] = (warningCounts[item] ?? 0) + 1 } else if (executable) { candidateCount += 1; executableCount += 1; warningCounts["executable-without-shebang"] = (warningCounts["executable-without-shebang"] ?? 0) + 1 } } return { filesScanned: files.length, scriptCandidates: candidateCount, shebangCount, executableScriptCount: executableCount, unreadableCount, interpreterCategories: interpreterCounts, portabilityWarnings: warningCounts, portabilityHint: warningCounts["machine-specific-interpreter-path"] ? "machine-specific-interpreters-found" : warningCounts["missing-executable-bit"] ? "scripts-may-not-launch-directly" : candidateCount === 0 ? "no-script-candidates-observed" : "no-coarse-portability-warning", valueFree: true, warning: "Only aggregate interpreter categories, executable state, and portability warning counts are returned. Paths, script text, project names, dependency names, command arguments, and environment values are never emitted." } }
export function format(value: unknown): string { const output = JSON.stringify(value, null, 2); return output.length <= MAX_OUTPUT ? output : JSON.stringify({ error: "Result exceeded the output budget and was reduced.", valueFree: true, truncated: true }) }
