import { execFile } from "node:child_process"
import { promisify } from "node:util"
import { realpath, stat } from "node:fs/promises"
import path from "node:path"
const exec = promisify(execFile)
const MAX_LINES = 10000
const MAX_OUTPUT = 12000
const DAY = 86400
export class ArchaeologyError extends Error {}
async function repoRoot(input: string): Promise<string> { const configured = process.env.GIT_ARCHAEOLOGY_ROOT ?? path.join(process.cwd(), ".."); const root = await realpath(path.resolve(configured)).catch(() => path.resolve(configured)); const requested = path.isAbsolute(input) ? input : path.resolve(root, input || "."); const target = await realpath(requested).catch(() => requested); const relative = path.relative(root, target); if (relative.startsWith("..") || path.isAbsolute(relative)) throw new ArchaeologyError("Repository path must stay inside the configured local workspace"); const info = await stat(target).catch(() => null); if (!info?.isDirectory()) throw new ArchaeologyError("Repository directory is unavailable"); return target }
async function git(cwd: string, args: string[], allowFailure = false): Promise<string> { try { const result = await exec("git", args, { cwd, timeout: 15000, maxBuffer: 2 * 1024 * 1024 }); return result.stdout.trim() } catch (error) { if (allowFailure && typeof error === "object" && error && "stdout" in error) return String((error as { stdout?: string }).stdout ?? "").trim(); throw new ArchaeologyError("Local Git metadata could not be read") } }
function ageBucket(timestamp: number, now = Math.floor(Date.now() / 1000)): string { const age = Math.max(0, now - timestamp); if (age < DAY) return "under-1-day"; if (age < 7 * DAY) return "1-to-7-days"; if (age < 30 * DAY) return "8-to-30-days"; if (age < 180 * DAY) return "31-to-180-days"; return "over-180-days" }
function buckets(timestamps: number[]): Record<string, number> { const out: Record<string, number> = { "under-1-day": 0, "1-to-7-days": 0, "8-to-30-days": 0, "31-to-180-days": 0, "over-180-days": 0 }; for (const timestamp of timestamps) out[ageBucket(timestamp)] += 1; return out }
function timestamps(output: string): number[] { return output.split(/\r?\n/).slice(0, MAX_LINES).map((line) => Number(line.trim())).filter((value) => Number.isFinite(value) && value > 0) }
async function assertGit(directory: string): Promise<void> { const inside = await git(directory, ["rev-parse", "--is-inside-work-tree"]); if (inside !== "true") throw new ArchaeologyError("Selected directory is not a Git work tree") }
export async function reflogSignals(input: string): Promise<Record<string, unknown>> { const root = await repoRoot(input); await assertGit(root); const times = timestamps(await git(root, ["reflog", "--all", "--format=%ct"])); const objectStats = await git(root, ["count-objects", "-v"], true); const loose = Number(objectStats.match(/^count: (\d+)/m)?.[1] ?? 0); const packs = Number(objectStats.match(/^in-pack: (\d+)/m)?.[1] ?? 0); return { reflogEntries: times.length, ageBuckets: buckets(times), looseObjectCount: loose, packedObjectCount: packs, recoveryHint: times.length === 0 ? "no-reflog-observations" : times.some((time) => ageBucket(time) === "under-1-day") ? "recent-history-may-be-recoverable" : "inspect-before-expiry", valueFree: true, warning: "Only aggregate timestamps and object counts are returned. Ref names, hashes, subjects, paths, remotes, and contents are never emitted." } }
export async function recoverySignals(input: string): Promise<Record<string, unknown>> { const root = await repoRoot(input); await assertGit(root); const output = await git(root, ["fsck", "--full", "--unreachable", "--no-reflogs", "--no-progress"], true); const counts: Record<string, number> = { commit: 0, tree: 0, blob: 0, tag: 0, other: 0 }; for (const line of output.split(/\r?\n/).slice(0, MAX_LINES)) { const match = line.match(/\b(?:unreachable|dangling)\s+(commit|tree|blob|tag)\b/); if (match) counts[match[1]] += 1; else if (/\b(?:unreachable|dangling)\s+\w+\b/.test(line)) counts.other += 1 } const total = Object.values(counts).reduce((sum, value) => sum + value, 0); return { unreachableObjectCount: total, objectTypes: counts, recoveryHint: counts.commit > 0 ? "unreachable-commits-found" : counts.blob > 0 || counts.tree > 0 ? "unreachable-supporting-objects-found" : "no-unreachable-objects-observed", valueFree: true, warning: "Only unreachable object type counts are returned. Object IDs, messages, paths, remotes, and contents are never emitted." } }
export async function stashSignals(input: string): Promise<Record<string, unknown>> { const root = await repoRoot(input); await assertGit(root); const times = timestamps(await git(root, ["stash", "list", "--format=%ct"])); return { stashCount: times.length, ageBuckets: buckets(times), recoveryHint: times.length > 0 ? "stashes-present" : "no-stashes-observed", valueFree: true, warning: "Only stash counts and age buckets are returned. Stash names, messages, hashes, paths, and contents are never emitted." } }
export function format(value: unknown): string { const output = JSON.stringify(value, null, 2); return output.length <= MAX_OUTPUT ? output : JSON.stringify({ error: "Result exceeded the output budget and was reduced.", valueFree: true, truncated: true }) }
