import { readFile, realpath, stat } from "node:fs/promises"
import path from "node:path"
const MAX_BYTES = 2 * 1024 * 1024
const MAX_OUTPUT = 14000
const MAX_KEYS = 10000
export class ContractDiffError extends Error {}
async function load(file: string): Promise<unknown> { const configured = process.env.CONTRACT_DIFF_ROOT ?? path.join(process.cwd(), ".."); const root = await realpath(path.resolve(configured)).catch(() => path.resolve(configured)); const requested = path.isAbsolute(file) ? file : path.resolve(root, file); const target = await realpath(requested).catch(() => requested); const relative = path.relative(root, target); if (relative.startsWith("..") || path.isAbsolute(relative)) throw new ContractDiffError("Snapshot path must stay inside the configured local workspace"); const info = await stat(target).catch(() => null); if (!info?.isFile() || info.size > MAX_BYTES) throw new ContractDiffError("Snapshot is missing or exceeds the local size limit"); try { return JSON.parse(await readFile(target, "utf8")) } catch { throw new ContractDiffError("Only valid JSON snapshots are supported") } }
function flatten(value: unknown, out: string[] = [], prefix = "#"): string[] { if (out.length >= MAX_KEYS) return out; if (Array.isArray(value)) { out.push(`${prefix}:array`); value.slice(0, 1000).forEach((item, index) => flatten(item, out, `${prefix}[]`)); return out } if (value && typeof value === "object") { const entries = Object.entries(value as Record<string, unknown>); out.push(`${prefix}:object`); for (const [key, child] of entries.slice(0, MAX_KEYS)) flatten(child, out, `${prefix}.${key.replace(/[^A-Za-z0-9_$-]/g, "_").slice(0, 80)}`); return out } out.push(`${prefix}:${typeof value}`); return out }
function digest(value: unknown): { count: number; kinds: Record<string, number> } { const keys = flatten(value); const kinds: Record<string, number> = {}; for (const key of keys) { const kind = key.split(":").at(-1) ?? "unknown"; kinds[kind] = (kinds[kind] ?? 0) + 1 } return { count: keys.length, kinds } }
export async function compareSnapshots(beforeFile: string, afterFile: string): Promise<Record<string, unknown>> { const before = digest(await load(beforeFile)); const after = digest(await load(afterFile)); const kinds = [...new Set([...Object.keys(before.kinds), ...Object.keys(after.kinds)])].sort(); const byKind = Object.fromEntries(kinds.map((kind) => [kind, { before: before.kinds[kind] ?? 0, after: after.kinds[kind] ?? 0, delta: (after.kinds[kind] ?? 0) - (before.kinds[kind] ?? 0) }])); return { beforeNodeCount: before.count, afterNodeCount: after.count, nodeDelta: after.count - before.count, changedShape: before.count !== after.count || kinds.some((kind) => before.kinds[kind] !== after.kinds[kind]), categories: byKind, valueFree: true, warning: "Only a coarse structural fingerprint with aggregate node counts and value-type categories is returned. This is not semantic compatibility analysis. Schema names, paths, values, descriptions, examples, versions, and file paths are never emitted." } }
export function format(value: unknown): string { const output = JSON.stringify(value, null, 2); return output.length <= MAX_OUTPUT ? output : JSON.stringify({ error: "Result exceeded the output budget and was reduced.", valueFree: true, truncated: true }) }
